# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2.1

orbs:
  php: circleci/php@1.1.0
  codecov: codecov/codecov@3.2.4

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - php/install-packages
      - codecov/upload

workflows:
  example-workflow:
    jobs:
      - example-job

steps:
  - run: checkout
  
  - save_cache:
        key: v1-dependencies-{{ checksum "composer.json" }}
        paths:
          - ./vendor
  - restore_cache:
       keys:
         - node-v1-{{ checksum "package.json" }}
         - node-v1-
  - run: yarn install
  - save_cache:
        key: node-v1-{{ checksum "package.json" }}
        paths:
          - node_modules

          
  # run tests with phpunit or codecept
  - run:
      name: install phpunit
      command: |
        wget https://phar.phpunit.de/phpunit-6.5.phar
        chmod +x phpunit-6.5.phar
        sudo mv phpunit-6.5.phar /usr/local/bin/phpunit
      

  - run:
     name: code coverage
     command: |
       mkdir htmlcov
       export XDEBUG_MODE=coverage 
       phpunit --coverage-clover clover.xml
     # phpunit --coverage-html htmlcov/coverage.html

  - run:
      name: prep upload cov 
      command: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov
          
  - store_artifacts:
     path: htmlcov