# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2.1

 
orbs:
  codecov: codecov/codecov@3.2.4

  

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout
      - run: php --version

      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
     
      # install dependencies    
  
      # run tests with phpunit or codecept
      - run:
         name: install phpunit
         command: |
            curl -LO https://phar.phpunit.de/phpunit-9.5.phar
            chmod +x phpunit-9.5.phar
            ./phpunit-9.5.phar --version --migrate-configuration
      
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules  

      - run:
         name: code coverage
         command: |
           export XDEBUG_MODE=coverage 
           ./phpunit-9.5.phar --coverage-clover clover.xml tests/


      - run:
         name: prep upload cov 
         command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov 
            chmod +x codecov
            ./codecov -t ${CODECOV_TOKEN}
            
     