jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - php/install-packages
workflows:
  example-workflow:
    jobs:
      - example-job